// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<string>}
 */
export function OpenFileDialog() {
    return $Call.ByID(2275595613);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(88318641, path);
}

/**
 * @param {string} currentName
 * @returns {$CancellablePromise<string>}
 */
export function SaveFileDialog(currentName) {
    return $Call.ByID(2993686416, currentName);
}

/**
 * @param {string} title
 * @returns {$CancellablePromise<void>}
 */
export function SetWindowTitle(title) {
    return $Call.ByID(3857593765, title);
}

/**
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(path, content) {
    return $Call.ByID(3601323672, path, content);
}
